sudo: required

language: node_js

node_js:
  - "4"

services:
  - docker

before_install:
  - pip install --user awscli

after_success:
  - scripts/staging/docker_push.sh


deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: scripts/staging/deploy.sh
    on:
      branch: dev
